#!/usr/bin/env bash
# W3a P1: write/update dossier stub for one repo (stub ≠ depth without ledger ids).
# Usage: dimension-synth-repo.sh <mother> <repo_id> [class1,class2,...]
set -euo pipefail
PKG_ROOT="$(cd "$(dirname "$0")/.." && pwd)"

fail() { echo "FAIL: $*" >&2; exit 1; }

[[ $# -ge 2 ]] || fail "usage: $0 <mother> <repo_id> [class1,class2,...]"
PARENT="$(cd "$1" && pwd)" || fail "mother not a directory: $1"
REPO_ID="$2"
CLASSES_CSV="${3:-dimension_behavior,dimension_tests,dimension_security,dimension_ops}"

[[ -f "$PARENT/docs/vibage/STATUS.md" ]] || fail "mother missing docs/vibage/STATUS.md"

OUT_DIR="$PARENT/docs/vibage/dossiers"
mkdir -p "$OUT_DIR"
OUT="$OUT_DIR/${REPO_ID}.md"

IFS=',' read -r -a CLASSES <<<"$CLASSES_CSV"

{
  echo "# Dimension dossier stub: ${REPO_ID}"
  echo
  echo "Generated by dimension-synth-repo.sh. **Stub alone ≠ depth / understood / full-sweep.**"
  echo "Cite ledger claim ids after dimension-search appends evidence."
  echo
  echo "## Planned claim classes"
  echo
  for c in "${CLASSES[@]}"; do
    c="$(echo "$c" | tr -d '[:space:]')"
    [[ -z "$c" ]] && continue
    echo "- \`${c}\` — pending ledger claim id"
  done
  echo
  echo "## Notes"
  echo
  echo "- Orchestrator: \`dimension-fill.sh\`"
  echo "- Searcher: \`dimension-search.sh\` (validate + ledger-append)"
  echo "- Verify: \`verify-dimension-fill.sh\` (exit 0 ≠ DIMENSION_FILL_OK alone as understood)"
} >"$OUT"

echo "OK: wrote $OUT"
